import type { Country, Continent } from "../types";

export const continentMap: Record<Country, Continent> = {
  HK: "Asia",
  US: "North America",
  DE: "Europe",
  IN: "Asia",
  BR: "South America",
  CA: "North America",
  CN: "Asia",
  FR: "Europe",
  JP: "Asia",
  MX: "North America",
  RU: "Europe",
  ZA: "Africa",
  NG: "Africa",
  AR: "South America",
  ES: "Europe",
  IT: "Europe",
};

export const proximityMap: Record<Continent, Record<Continent, number>> = {
  Asia: {
    Asia: 0,
    Europe: 1,
    Oceania: 2,
    Africa: 3,
    "North America": 4,
    "South America": 5,
    Antarctica: 6,
  },
  Africa: {
    Africa: 0,
    Europe: 1,
    Asia: 2,
    "South America": 3,
    "North America": 4,
    Oceania: 5,
    Antarctica: 6,
  },
  "North America": {
    "North America": 0,
    "South America": 1,
    Europe: 2,
    Asia: 3,
    Africa: 4,
    Oceania: 5,
    Antarctica: 6,
  },
  "South America": {
    "South America": 0,
    "North America": 1,
    Africa: 2,
    Europe: 3,
    Asia: 4,
    Oceania: 5,
    Antarctica: 6,
  },
  Antarctica: {
    Antarctica: 0,
    "South America": 1,
    Africa: 2,
    Oceania: 3,
    Asia: 4,
    Europe: 5,
    "North America": 6,
  },
  Europe: {
    Europe: 0,
    Africa: 1,
    Asia: 2,
    "North America": 3,
    "South America": 4,
    Oceania: 5,
    Antarctica: 6,
  },
  Oceania: {
    Oceania: 0,
    Asia: 1,
    "North America": 2,
    "South America": 3,
    Africa: 4,
    Europe: 5,
    Antarctica: 6,
  },
};
